from .aspects import *

to_string_table = {
    AER: "Aer",
    ALIENSIS: "Aliensis",
    AQUA: "Aqua",
    ARBOR: "Arbor",
    AURAM: "Auram",
    BESTIA: "Bestia",
    COGNITIO: "Cognitio",
    CORPUS: "Corpus",
    DESIDIA: "Desidia",
    EXANIMIS: "Exanimis",
    FABRICO: "Fabrico",
    FAMES: "Fames",
    GELUM: "Gelum",
    GULA: "Gula",
    HERBA: "Herba",
    HUMANUS: "Humanus",
    IGNIS: "Ignis",
    INFERNUS: "Infernus",
    INSTRUMENTUM: "Instrumentum",
    INVIDIA: "Invidia",
    IRA: "Ira",
    ITER: "Iter",
    LIMUS: "Limus",
    LUCRUM: "Lucrum",
    LUX: "Lux",
    LUXURIA: "Luxuria",
    MACHINA: "Machina",
    MESSIS: "Messis",
    METALLUM: "Metallum",
    METO: "Meto",
    MORTUUS: "Mortuus",
    MOTUS: "Motus",
    ORDO: "Ordo",
    PANNUS: "Pannus",
    PERDITIO: "Perditio",
    PERFODIO: "Perfodio",
    PERMUTATIO: "Permutatio",
    POTENTIA: "Potentia",
    PRAECANTATIO: "Praecantatio",
    SANO: "Sano",
    SENSUS: "Sensus",
    SPIRITUS: "Spiritus",
    SUPERBIA: "Superbia",
    TELUM: "Telum",
    TEMPESTAS: "Tempestas",
    TEMPUS: "Tempus",
    TENEBRAE: "Tenebrae",
    TERMINUS: "Terminus",
    TERRA: "Terra",
    TUTAMEN: "Tutamen",
    VACUOS: "Vacuos",
    VENEMUM: "Venemum",
    VICTUS: "Victus",
    VINCULUM: "Vinculum",
    VITIUM: "Vitium",
    VITREUS: "Vitreus",
    VOLATUS: "Volatus",
}


def to_string(aspect: AspectType) -> str:
    return to_string_table[aspect]
